"use client";

import { useRef, useState } from "react";
import { Download, ImagePlus, RotateCcw, Upload } from "lucide-react";
import { toPng } from "html-to-image";

type Player = { name: string; number: string; position: string; image: string; x: number; y: number };
const presets: Record<string, { x: number; y: number }[]> = {
  "4-3-3": [{x:50,y:91},{x:15,y:75},{x:38,y:78},{x:62,y:78},{x:85,y:75},{x:25,y:57},{x:50,y:61},{x:75,y:57},{x:18,y:34},{x:50,y:25},{x:82,y:34}],
  "4-2-3-1": [{x:50,y:91},{x:15,y:75},{x:38,y:78},{x:62,y:78},{x:85,y:75},{x:35,y:60},{x:65,y:60},{x:20,y:39},{x:50,y:35},{x:80,y:39},{x:50,y:22}],
  "3-4-3": [{x:50,y:91},{x:28,y:76},{x:50,y:80},{x:72,y:76},{x:10,y:53},{x:35,y:58},{x:65,y:58},{x:90,y:53},{x:20,y:32},{x:50,y:25},{x:80,y:32}],
};
const fa=(v:string)=>v.replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[Number(d)]);
const blank=()=>Array.from({length:11},(_,i)=>({name:"",number:"",position:"",image:"",...presets["4-3-3"][i]}));
const read=(file:File,set:(v:string)=>void)=>{const r=new FileReader();r.onload=()=>set(String(r.result));r.readAsDataURL(file)};
const pitchSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 1400"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#173d25"/><stop offset=".5" stop-color="#0d2b19"/><stop offset="1" stop-color="#1a4828"/></linearGradient><pattern id="m" width="90" height="90" patternUnits="userSpaceOnUse"><rect width="90" height="90" fill="url(#g)"/><path d="M0 0h90v90H0z" fill="none" stroke="#fff" stroke-opacity=".025" stroke-width="2"/></pattern></defs><rect width="900" height="1400" fill="url(#m)"/><g fill="none" stroke="#fff" stroke-opacity=".42" stroke-width="7"><rect x="35" y="35" width="830" height="1330" rx="24"/><path d="M35 700h830M260 35v270h380V35M260 1365v-270h380v270"/><circle cx="450" cy="700" r="110"/><circle cx="450" cy="700" r="7" fill="#fff"/></g><g fill="#fff" fill-opacity=".035"><path d="M0 100h900v100H0zM0 300h900v100H0zM0 500h900v100H0zM0 700h900v100H0zM0 900h900v100H0zM0 1100h900v100H0zM0 1300h900v100H0z"/></g></svg>`;
const pitchBackground=`url("data:image/svg+xml,${encodeURIComponent(pitchSvg)}")`;

export default function TeamLineupTool(){
 const canvas=useRef<HTMLDivElement>(null); const [formation,setFormation]=useState("4-3-3"); const [title,setTitle]=useState("ترکیب تراکتور"); const [subtitle,setSubtitle]=useState("ترکیب اصلی"); const [tournament,setTournament]=useState("لیگ برتر ایران"); const [coach,setCoach]=useState("نام سرمربی"); const [coachImage,setCoachImage]=useState(""); const [brand,setBrand]=useState("tractorFan1970"); const [match,setMatch]=useState("ترکیب احتمالی"); const [logo,setLogo]=useState(""); const [players,setPlayers]=useState<Player[]>(blank); const [downloading,setDownloading]=useState(false); const [drag,setDrag]=useState<number|null>(null);
 const applyFormation=(value:string)=>{setFormation(value);setPlayers(p=>p.map((x,i)=>({...x,...presets[value][i]})))};
 const update=(i:number,k:keyof Player,v:string)=>setPlayers(p=>p.map((x,n)=>n===i?{...x,[k]:v}:x));
 const move=(i:number,e:React.PointerEvent)=>{const el=canvas.current?.querySelector("[data-pitch]") as HTMLElement|null;if(!el)return;const r=el.getBoundingClientRect();const x=Math.max(7,Math.min(93,((e.clientX-r.left)/r.width)*100));const y=Math.max(7,Math.min(93,((e.clientY-r.top)/r.height)*100));setPlayers(p=>p.map((xv,n)=>n===i?{...xv,x,y}:xv));};
 const download=async()=>{if(!canvas.current)return;setDownloading(true);try{const u=await toPng(canvas.current,{width:1080,height:1350,pixelRatio:2,cacheBust:true});const a=document.createElement("a");a.download="tractor-lineup.png";a.href=u;a.click()}finally{setDownloading(false)}};
 const reset=()=>{setFormation("4-3-3");setTitle("ترکیب تراکتور");setSubtitle("ترکیب اصلی");setTournament("لیگ برتر ایران");setCoach("نام سرمربی");setCoachImage("");setBrand("tractorFan1970");setMatch("ترکیب احتمالی");setLogo("");setPlayers(blank())};
 return <main className="min-h-screen bg-[#070707] px-4 py-8 text-white md:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[390px_1fr]">
  <section className="rounded-3xl border border-white/10 bg-[#111] p-5"><span className="text-xs font-bold tracking-widest text-[#d4a72c]">TRAXTOR LINEUP TOOL</span><h1 className="mt-2 text-2xl font-black">شماتیک ترکیب تیم</h1><p className="mt-2 text-sm text-white/45">آرایش را انتخاب یا جایگاه بازیکنان را آزادانه جابه‌جا کنید.</p><div className="mt-6 space-y-3">
   <input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان" className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input value={subtitle} onChange={e=>setSubtitle(e.target.value)} placeholder="زیرعنوان" className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/>
   <div className="grid grid-cols-2 gap-2"><input value={tournament} onChange={e=>setTournament(e.target.value)} placeholder="تورنمنت" className="rounded-xl border border-white/10 bg-black/30 px-3 py-3"/><input value={match} onChange={e=>setMatch(e.target.value)} placeholder="وضعیت" className="rounded-xl border border-white/10 bg-black/30 px-3 py-3"/></div>
   <div className="grid grid-cols-2 gap-2"><input value={coach} onChange={e=>setCoach(e.target.value)} placeholder="نام سرمربی" className="rounded-xl border border-white/10 bg-black/30 px-3 py-3"/><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-white/10 text-sm"><Upload size={15}/> عکس سرمربی<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&read(e.target.files[0],setCoachImage)}/></label></div>
   <input value={brand} onChange={e=>setBrand(e.target.value.replace(/^@/,''))} placeholder="آیدی رسانه بدون @" className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/>
   <div className="grid grid-cols-2 gap-2"><select value={formation} onChange={e=>applyFormation(e.target.value)} className="rounded-xl border border-white/10 bg-[#181818] px-4 py-3"><option>4-3-3</option><option>4-2-3-1</option><option>3-4-3</option></select><button onClick={()=>setFormation("custom")} className="rounded-xl border border-[#d4a72c]/30 bg-[#d4a72c]/10 px-4 py-3 text-sm font-bold text-[#d4a72c]">آرایش سفارشی</button></div>
   <label className="flex cursor-pointer items-center justify-between rounded-xl border border-dashed border-white/15 bg-black/20 px-4 py-3 text-sm"><span className="flex items-center gap-2"><Upload size={16}/> لوگوی رسانه</span><span className="text-[#d4a72c]">انتخاب<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&read(e.target.files[0],setLogo)}/></span></label>
   <div className="h-px bg-white/10"/>
   {players.map((p,i)=><div key={i} className="rounded-2xl border border-white/10 bg-black/20 p-3"><div className="mb-2 flex justify-between text-xs text-[#d4a72c]">بازیکن {fa(String(i+1))}<label className="cursor-pointer text-white/50"><ImagePlus size={14} className="inline"/> عکس<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&read(e.target.files[0],v=>update(i,"image",v))}/></label></div><div className="grid grid-cols-[1fr_65px] gap-2"><input value={p.name} onChange={e=>update(i,"name",e.target.value)} placeholder="نام بازیکن" className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm"/><input value={p.number} onChange={e=>update(i,"number",e.target.value)} placeholder="شماره" className="rounded-lg border border-white/10 bg-white/5 px-2 py-2 text-sm"/><input value={p.position} onChange={e=>update(i,"position",e.target.value)} placeholder="پست" className="col-span-2 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm"/></div></div>)}
   <div className="flex gap-2"><button onClick={download} disabled={downloading} className="flex-1 rounded-xl bg-[#d71920] px-4 py-3 font-bold">{downloading?"در حال ساخت...":"دانلود PNG"}</button><button onClick={reset} className="h-12 w-12 rounded-xl border border-white/10 bg-white/5"><RotateCcw size={18}/></button></div>
  </div></section>
  <section className="flex items-start justify-center rounded-3xl border border-white/10 bg-[#0d0d0d] p-3 md:p-6"><div className="w-full max-w-[540px] overflow-auto rounded-2xl bg-black p-2"><div ref={canvas} style={{width:1080,height:1350,transform:"scale(.5)",transformOrigin:"top left",marginBottom:-675}} className="relative overflow-hidden bg-[#090909] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_10%,rgba(215,25,32,.38),transparent_28%),linear-gradient(160deg,#070707,#17090b 55%,#080808)]"/><div className="absolute -right-16 top-16 h-[220px] w-[220px] rounded-full border-[28px] border-[#d71920]/10"/><div className="relative h-full px-[70px] py-[55px]"><div className="flex items-start justify-between"><div><div className="text-[24px] font-black tracking-[8px] text-[#d4a72c]">TRAXTOR</div><h2 className="mt-2 text-[58px] font-black">{title}</h2><div className="mt-2 text-[21px] font-bold text-white/35">{subtitle} • {tournament}</div><div className="mt-3 inline-block rounded-full border border-[#d71920]/50 px-5 py-2 text-[19px] text-[#d71920]">{match}</div></div>{logo?<img src={logo} className="h-[100px] w-[100px] rounded-full border-4 border-[#d4a72c] object-contain p-2"/>:<div className="flex h-[100px] w-[100px] items-center justify-center rounded-full border-4 border-[#d71920] text-[35px] font-black">T</div>}</div>
    <div data-pitch className="relative mt-8 h-[900px] overflow-hidden rounded-[42px] border-2 border-white/10 bg-[#12301d] bg-cover bg-center shadow-2xl" style={{backgroundImage:pitchBackground}}>
      {players.map((p,i)=><div key={i} onPointerDown={e=>{setDrag(i);(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}} onPointerMove={e=>drag===i&&move(i,e)} onPointerUp={()=>setDrag(null)} className="absolute z-10 -translate-x-1/2 -translate-y-1/2 cursor-grab select-none active:cursor-grabbing" style={{left:`${p.x}%`,top:`${p.y}%`}}><div className="relative flex h-[96px] w-[96px] items-center justify-center rounded-full border-[5px] border-[#d71920] bg-[#121212] shadow-xl ring-2 ring-black/40">{p.image?<img src={p.image} className="h-full w-full rounded-full object-cover"/>:<span className="text-[27px] font-black text-white/20">{fa(String(i+1))}</span>}<span className="absolute -right-2 -top-2 flex h-[34px] w-[34px] items-center justify-center rounded-full bg-[#d4a72c] text-[16px] font-black text-black">{fa(p.number||String(i+1))}</span></div><div className="mt-1 max-w-[128px] truncate rounded-md border border-white/10 bg-black/90 px-2 py-1 text-center text-[17px] font-black shadow-lg">{p.name||`بازیکن ${fa(String(i+1))}`}</div><div className="text-center text-[12px] font-bold text-[#d4a72c]">{p.position||"بازیکن"}</div></div>)}
    </div>
    <div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4"><div className="flex items-center gap-3">{coachImage?<img src={coachImage} className="h-[58px] w-[58px] rounded-full object-cover ring-2 ring-[#d4a72c]"/>:<div className="h-[58px] w-[58px] rounded-full bg-white/5"/>}<div><div className="text-[16px] text-white/40">سرمربی</div><div className="text-[22px] font-black">{coach}</div></div></div><div className="text-[20px] font-bold text-white/35">{brand.replace(/^@/,"")}</div></div></div>
  </div></div></section>
 </div></main>;
}
