import { BarChart3, CircleUserRound, LayoutTemplate, Newspaper, Trophy, Users, Table2, ArrowLeftRight, Award, GitCompareArrows, Goal, HandCoins } from "lucide-react";
export type Tool={id:string;title:string;description:string;category:string;icon:typeof Trophy;available:boolean;themeIds?:string[];supportsCustomFields?:boolean};
export const tools:Tool[]=[
{id:"top-players",title:"۵ بازیکن برتر",description:"ساخت طرح حرفه‌ای رتبه‌بندی پنج بازیکن برتر با عکس، تیم و امتیاز.",category:"آمار و رتبه‌بندی",icon:Trophy,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"ranking",title:"طرح‌های آماری و رتبه‌بندی",description:"یک ابزار چندکاره برای بهترین بازیکنان، گلزنان، پاسورها، کلین‌شیت و دیگر شاخص‌های آماری.",category:"آمار و رتبه‌بندی",icon:Trophy,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"top-scorers",title:"بهترین گلزنان",description:"ساخت طرح رتبه‌بندی بهترین گلزنان با آمار گل و اطلاعات بازیکن.",category:"آمار و رتبه‌بندی",icon:Goal,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"top-assists",title:"بهترین پاسورها",description:"ساخت طرح رتبه‌بندی بهترین پاسورها با آمار پاس گل.",category:"آمار و رتبه‌بندی",icon:HandCoins,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"goalkeepers",title:"بهترین دروازه‌بان‌ها",description:"ساخت طرح آمار دروازه‌بان‌ها با کلین‌شیت، مهار و درصد موفقیت.",category:"آمار و رتبه‌بندی",icon:Goal,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"lineup",title:"ترکیب تیم",description:"ساخت شماتیک ترکیب تیم روی زمین فوتبال با آرایش دلخواه.",category:"ترکیب",icon:Users,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"player-card",title:"کارت بازیکن",description:"ساخت کارت گرافیکی بازیکن همراه با مشخصات و آمار.",category:"بازیکنان",icon:CircleUserRound,available:true,themeIds:["tractor-red","stadium-night","classic-red"]},
{id:"team-stats",title:"آمار تیم",description:"نمایش آمار و عملکرد یک تیم در قالب یک طرح گرافیکی.",category:"آمار",icon:BarChart3,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"news-card",title:"طرح خبر",description:"ساخت کارت گرافیکی حرفه‌ای برای اخبار و اطلاعیه‌های فوتبالی.",category:"اخبار",icon:Newspaper,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"league-table",title:"جدول لیگ",description:"ساخت طرح گرافیکی جدول مسابقات با امکان برجسته‌سازی تیم موردنظر.",category:"مسابقات",icon:Table2,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"transfer",title:"طرح نقل‌وانتقال",description:"ساخت طرح اختصاصی برای انتقال بازیکن، ورود، خروج و وضعیت قرارداد.",category:"نقل‌وانتقالات",icon:ArrowLeftRight,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"player-week",title:"بازیکن هفته",description:"ساخت طرح افتخاری بازیکن برتر هفته با تصویر و آمار عملکرد.",category:"بازیکنان",icon:Award,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"match-result",title:"نتیجه بازی",description:"ساخت طرح نتیجه مسابقه با لوگو، نتیجه و اطلاعات بازی.",category:"مسابقات",icon:Trophy,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"match-stats",title:"آمار بازی",description:"ساخت طرح گرافیکی مقایسه آمار مسابقه بین دو تیم.",category:"آمار",icon:BarChart3,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"player-comparison",title:"مقایسه دو بازیکن",description:"مقایسه حرفه‌ای دو بازیکن با عکس، مشخصات و آمار قابل تنظیم.",category:"بازیکنان",icon:GitCompareArrows,available:true,themeIds:["tractor-red","stadium-night","classic-red"],supportsCustomFields:true},
{id:"custom-template",title:"قالب اختصاصی",description:"ساخت و شخصی‌سازی قالب‌های گرافیکی برای رسانه.",category:"قالب‌ها",icon:LayoutTemplate,available:false},
];
